language: node_js
node_js:
  - 'stable'
install: npm install

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE companiestest;' -U postgres

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

addons:
  postgresql: "9.6"

